### ISSUE TITLE
Graalvm can compile and package normally, but cannot load the data source after startup

### ISSUE THREAD

**Issue by liao-can-jie** [baomidou/dynamic-datasource#535]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment
Window10
JDK Version(required): 
java version "17.0.7" 2023-04-18 LTS
SpringBoot Version(required): 
3.1.1
dynamic-datasource-spring-boot-starter Version(required):
4.1.1
druid Version(optional):
java version "17.0.7" 2023-04-18 LTS

# Describe what happened
graalvm可正常编译打包，启动后加载不到数据源

Expected Result:
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/70512659/eead30ea-9575-4356-8761-bdd38c94c0af)

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
作者表示学了一下午还不会native,请在https://github.com/dynamic-datasource/dynamic-datasource-samples/tree/master/springboot3-sample 提交PR并补充打包过程和复现过程.....

**Comment by huayanYu** [comment]
等待有缘人吧, 我跑起来错误不一样

**Comment by liao-can-jie** [comment]
> 等待有缘人吧, 我跑起来错误不一样
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/70512659/e2e54c1a-b5b5-4ef4-8ad4-7523890ef291)
mvn -Pnative native:compile 之前先执行【java -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image  -jar  target\springboot3-sample-1.0.0.jar】

**Comment by liao-can-jie** [comment]
![image](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/70512659/375ac542-a52c-40d0-889a-3c7d76b25479)
没有更改里面【https://github.com/dynamic-datasource/dynamic-datasource-samples/tree/master/springboot3-sample】的代码，能正常编译
