### ISSUE TITLE
TransactionalTemplate里使用到了mybatis-plus的工具类

### ISSUE THREAD

**Issue by zzzombie207** [baomidou/dynamic-datasource#539]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
8
SpringBoot Version(required): 
2.3
dynamic-datasource-spring-boot-starter Version(required):
4.1.1
druid Version(optional):
1.2.14

# Describe what happened

Expected Result:
在不引入mybatis-plus的情况下能使用所有功能

Actual Result:
TransactionalTemplate的ArrayUtils是引用的mybatis-plus的工具类，项目没有使用mybatis-plus，产生java.lang.NoClassDefFoundError

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
1
