### ISSUE TITLE
DSTransactional 注解拦截器 bug

### ISSUE THREAD

**Issue by afish177** [baomidou/dynamic-datasource#542]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment
idea
JDK Version(required): 1.8

SpringBoot Version(required): 2.7.13

dynamic-datasource-spring-boot-starter Version(required):4.1.3

druid Version(optional):1.2.18

# Describe what happened
调用登录方法时 我有userservice类得getUSerEntity方法(此方法未加DSTr注解) 会进入DynamicLocalTransactionInterceptor 拦截方法 扫描此DSTransactional  注解 会出现null 异常 导出报错 如图 (是否是 我哪里没设置 还是 的确有这个问题)

![image](https://github.com/baomidou/dynamic-datasource/assets/32056262/c2edef01-a0bd-4e39-bd9d-3b6f8fb3e026)
![image](https://github.com/baomidou/dynamic-datasource/assets/32056262/da98a956-82a8-4f5a-a55a-8903641b3e43)
![image](https://github.com/baomidou/dynamic-datasource/assets/32056262/ca6af114-1c1a-446d-8de4-2fabaebe63b1)

![image](https://github.com/baomidou/dynamic-datasource/assets/32056262/1d3fd710-ad97-4a1f-b2d6-d09c41349ed1)

麻烦大佬看下 谢谢 赶紧
Expected Result:

期待登录成功

Actual Result:

报错
If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by ZPZP1** [comment]
@DSTransactional 加在接口上了吗
