### ISSUE TITLE
druid配置类与druid官方配置类属性不一致问题，导致连接池配置不符合预期

### ISSUE THREAD

**Issue by lingfengcoder** [baomidou/dynamic-datasource#546]
# Enviroment

JDK Version(required): 1.8.333

SpringBoot Version(required): 2.0.5.RELEASE

dynamic-datasource-spring-boot-starter Version(required):  4.1.2

druid Version(optional): 1.1.23

# Describe what happened
1.在配置 druid的filters时，配置类根本没有filter字段，所以使用反射方法没有任何意义，因为获取不到任何结果
![图片](https://github.com/baomidou/dynamic-datasource/assets/30565113/40c9df95-7dde-46eb-925d-4edb8c281005)

2.druid 配置文件中 connectionProperties 字段设置的属性与druid原生不一致，导致属性设置失败
![图片](https://github.com/baomidou/dynamic-datasource/assets/30565113/f211768a-8893-494d-ad8d-e6d0ceb49caf)

Expected Result:
请求调整和druid原生配置保持一致

**Comment by huayanYu** [comment]
第一个4.1.3已经解决.  第二个你确定不能设置么? druid原生有两个设置connectionProperties的方法,一个是string一个是properties

**Comment by lingfengcoder** [comment]
第二个，druid的做法也是先将字符串转换成properties
![图片](https://github.com/baomidou/dynamic-datasource/assets/30565113/88b69f6c-9f5c-485b-b675-81ee046a8fdc)
而dynamic中的com.baomidou.dynamic.datasource.creator.druid.DruidConfig 的connectionProperties 属性直接就是properties spring不能直接注入，比如当connectionProperties的值为 config.decrypt.key=${xx.mysql.druid.publickey},当然这个也可能是由于我的springboot版本过低2.0.5 造成的
![图片](https://github.com/baomidou/dynamic-datasource/assets/30565113/fe69578c-b418-478b-957c-00bdd9470a12)

**Comment by huayanYu** [comment]
你可以写一个demo我看下. 不知道你具体怎么写的.

**Comment by lingfengcoder** [comment]
![图片](https://github.com/baomidou/dynamic-datasource/assets/30565113/8f1909fc-a686-4b22-b232-b7b55376fb99)
下面是demo
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: ${spring.datasource.druid.url}
          username: ${spring.datasource.druid.username}
          password: ${spring.datasource.druid.password}
          driver-class-name: ${spring.datasource.druid.driver-class-name}
          type: ${spring.datasource.type}
          druid:
            max-active: ${spring.datasource.druid.max-active}
            max-wait: ${spring.datasource.druid.max-wait}
            min-idle: ${spring.datasource.druid.min-idle}
            initial-size: ${spring.datasource.druid.initial-size}
            max-pool-prepared-statement-per-connection-size: ${spring.datasource.druid.max-pool-prepared-statement-per-connection-size}
            time-between-eviction-runs-millis: ${spring.datasource.druid.time-between-eviction-runs-millis}
            min-evictable-idle-time-millis: ${spring.datasource.druid.min-evictable-idle-time-millis}
            test-while-idle: ${spring.datasource.druid.test-while-idle}
            test-on-borrow: ${spring.datasource.druid.test-on-borrow}
            test-on-return: ${spring.datasource.druid.test-on-return}
            pool-prepared-statements: ${spring.datasource.druid.pool-prepared-statements}
            connection-properties: ${spring.datasource.druid.connection-properties}
            filters: ${spring.datasource.druid.filters}
            public-key: ${xx.mysql.druid.publickey}

**Comment by huayanYu** [comment]
不能引用， 而且全局參數有全局參數的設置方法。
