### ISSUE TITLE
Jdk11 JPMS ，存在split package问题

### ISSUE THREAD

**Issue by ipwwp-git** [baomidou/dynamic-datasource#547]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
jdk11
SpringBoot Version(required): 
2.7.12
dynamic-datasource-spring-boot-starter Version(required):
4.1.3
druid Version(optional):

# Describe what happened
因为dynamic-datasource-creator 和 dynamic-datasource-spring2个jar文件，下面的包名有很多重复的，比如toolkit，在JPMS的工作机制下，存在分裂包的问题(split package)，导致程序无法编译通过

Expected Result:

将包名变更下，不要完全一致，满足JPMS的规范

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
JPMS 是啥??? 为什么要同时引入两个包????

**Comment by huayanYu** [comment]
无回复,关闭.

**Comment by ipwwp-git** [comment]
JPMS就是Java Platform Module System，jdk9引入的模块化系统

**Comment by ipwwp-git** [comment]
maven引入dynamic-datasource-spring-boot-starter后，会自动引入依赖包dynamic-datasource-spring 和 dynamic-datasource-creator

![image](https://github.com/baomidou/dynamic-datasource/assets/126652127/b2b85f8a-10d9-4576-988a-15f6d47304fd)
