### ISSUE TITLE
The project's sponsor URL is broken

### ISSUE THREAD

**Issue by linghengqian** [baomidou/dynamic-datasource#569]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): `GraalVM CE Dev 24.0.0 For JDK22`

SpringBoot Version(required): `3.2.0-SNAPSHOT`

dynamic-datasource-spring-boot-starter Version(required): `4.2.0-SNAPSHOT`

druid Version(optional):

# Describe what happened

- The project's sponsor URL is broken. Refer to https://dynamic-datasource.com/guide/donate/ .
- ![image](https://github.com/baomidou/dynamic-datasource/assets/20187731/85d05e77-950e-4059-a265-c71084d28d77)

Expected Result:

- The project's sponsor URL is not broken.

Actual Result:

- The project's sponsor URL is broken.

# Steps to reproduce

- Step 1 

- Open https://github.com/baomidou/dynamic-datasource.

- Step 2 

- Open https://dynamic-datasource.com/guide/donate/ .

**Comment by huayanYu** [comment]
removed
