### ISSUE TITLE
Spring注解事务Mybaits Dao搭配JdbcTemplate事务挂起,锁死

### ISSUE THREAD

**Issue by GongLe** [baomidou/dynamic-datasource#572]
![image](https://github.com/baomidou/dynamic-datasource/assets/1720495/085ac22a-dbb0-4202-a101-8e83106b0803)

您好，使用Spring注解事务Mybaits Dao搭配JdbcTemplate事务挂起,锁死，且日志不报错，请问有类似的反馈吗？
Service包含查询和修改，方法体同时包含JdbcTemplate修改

**Comment by GongLe** [comment]
Datasource都为master，事务管理器现实声明了，移除动态数据源即恢复正常
![image](https://github.com/baomidou/dynamic-datasource/assets/1720495/23d3630d-23c7-44e4-afdd-69348fe02046)

**Comment by ZPZP1** [comment]
Spring事务管理器会取第一次开启事务的链接是不支持数据源切换的

**Comment by GongLe** [comment]
> Spring事务管理器会取第一次开启事务的链接,是不支持数据源切换的

在方法内都没进行数据源切换，都用的master

**Comment by ZPZP1** [comment]
> > Spring事务管理器会取第一次开启事务的链接,是不支持数据源切换的
> 
> 在方法内都没进行数据源切换，都用的master

你是既用了mybatis又用了jdbctemplate，spring事务管理器在纯在事务时会取事务保存的连接，感觉和数据源关系不大，你可以看下两次取了的数据源是不是同一个，如果是可以写个例子复现，我们去排查，贴了这两个截图看不出什么

**Comment by ZPZP1** [comment]
也可以使用@DStransationl看看能否解决

**Comment by GongLe** [comment]
> > > Spring事务管理器会取第一次开启事务的链接,是不支持数据源切换的
> > 
> > 
> > 在方法内都没进行数据源切换，都用的master
> 
> 你是既用了mybatis又用了jdbctemplate，spring事务管理器在纯在事务时会取事务保存的连接，感觉和数据源关系不大，你可以看下两次取了的数据源是不是同一个，如果是可以写个例子复现，我们去排查，贴了这两个截图看不出什么
感谢！问题解决了，果然是载入datasource问题，我以为DynamicRoutingDataSource和DataSource dynamicDataSource都是master就没事，还请解释布道一下哈！
![image](https://github.com/baomidou/dynamic-datasource/assets/1720495/2aa99502-c377-4f69-8188-517139a12f69)
![image](https://github.com/baomidou/dynamic-datasource/assets/1720495/3a9a1488-53ae-4a7a-ab5f-78b93e85f11f)

**Comment by ZPZP1** [comment]
DynamicRoutingDataSource是做数据源路由的基类，不是具体的Datasource
