### ISSUE TITLE
多数据源事务没有按预期提交

### ISSUE THREAD

**Issue by rongjiangfeng** [baomidou/dynamic-datasource#573]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment
CentOS Linux release 7.8.2003 (Core)

JDK Version(required): 
1.8

SpringBoot Version(required): 
2.2.4.RELEASE

dynamic-datasource-spring-boot-starter Version(required):
3.5.2

druid Version(optional):

# Describe what happened
一个service方法添加@DSTransactional注解，里面有2个操作
1、先插入从库数据
2、删除主库数据
有时候会出现 2、的事务提交了，但是1、的事务没有提交，但是也没有报错

Expected Result:
预期结果是2个一起提交，或者有报错就回滚

Actual Result:
只提交了主库的事务，但不是每次都这样

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by ZPZP1** [comment]
按照以下步骤排查：
 1.使用最新依赖
 2.检查数据库引擎是否支持事务
 3. 在示例项目中复现，只有文字描述无法排查

**Comment by rongjiangfeng** [comment]
没事了，是本身mybatis，insert标签插入多条记录，第一条成功，后面失败的话，就不会报错导致的
