### ISSUE TITLE
读写分离无效问题

### ISSUE THREAD

**Issue by amoslam1** [baomidou/dynamic-datasource#574]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 1.5.22.RELEASE

dynamic-datasource-spring-boot-starter Version(required):3.0.0

druid Version(optional):1.2.6

# Describe what happened

我想使用dynamic-datasource实现读写分离，但无效

Expected Result:

Actual Result:

![image](https://github.com/baomidou/dynamic-datasource/assets/45059387/587c1433-a2b0-4830-8f9b-8cb3e0c1d7e0)

![image](https://github.com/baomidou/dynamic-datasource/assets/45059387/6f3008ff-94d3-4a32-bffe-f48e64a41d23)

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by amoslam1** [comment]
大佬们，这是什么原因导致的？本地配置问题？

**Comment by amoslam1** [comment]
各位大佬，麻烦帮忙看看，感谢感谢

**Comment by ZPZP1** [comment]
先用新版本试试，肯定会走Plugin.wrap，然后走拦截的逻辑

**Comment by amoslam1** [comment]
> 先用新版本试试，肯定会走Plugin.wrap，然后走拦截的逻辑

改成新版本可以了，但是又有个问题，类似用分页工具的，PageHelperAutoConfiguration会输出2条SQL，一条是count，一条是查结果,在代码里面,我看了push 之后就clear掉了，这样会不会导致拦截count的时候clear了，再执行查结果的时候导致路由回默认库了？

![image](https://github.com/baomidou/dynamic-datasource/assets/45059387/8c9394e3-7c6a-46c7-b3a7-0c2dbfbc02c5)

我这里有6个数据源，我想实现的效果就是其中2个数据源走读写分离，其他还是正常走

**Comment by huayanYu** [comment]
你可以根据你的情况自己改,一共就几行代码
