### ISSUE TITLE
jpa多层数据源嵌套切换失效 。（ServiceA >>> ServiceB >>> ServiceC）。

### ISSUE THREAD

**Issue by zlyou** [baomidou/dynamic-datasource#575]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): jdk17

SpringBoot Version(required): 3.1.0

dynamic-datasource-spring-boot-starter Version(required):v4.1.3

druid Version(optional):1.2.17

# Describe what happened

Expected Result:
jpa多层数据源嵌套切换失效 。（ServiceA >>> ServiceB >>> ServiceC）。
 ServiceB 对应的数据库master
 ServiceC对应的数据库slave
当执行ServiceC方法使用的是库slave
Actual Result:
期望ServiceB 使用库master
期望ServiceC使用库slave
If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
jpa 自帶事務，得找JPA支持
