### ISSUE TITLE
Jdk11 JPMS ，存在split package问题

### ISSUE THREAD

**Issue by ipwwp-git** [baomidou/dynamic-datasource#576]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):
jdk11
SpringBoot Version(required):
2.7.12
dynamic-datasource-spring-boot-starter Version(required):
4.1.3
druid Version(optional):

# Describe what happened
描述参考：#547 (https://github.com/baomidou/dynamic-datasource/issues/547)

Expected Result:

将包名变更下，不要完全一致，满足JPMS的规范

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
看不懂,什么编译不过?

**Comment by ZPZP1** [comment]
应该是说的dynamic-datasource-spring-boot-starter引入了Dynamic-datasource-creator和Dynamic-datasource-spring这两个模块的依赖，这两个模块中含有相同的包com.baomidou.dynamic.datasource.toolkit。当jdk9下模块化编译进行对外exports暴漏pakage时有包分裂的问题，应该一下不同模块包路径相同这种情况的包名

**Comment by huayanYu** [comment]
@ZPZP1 我是jar提供给别人啊,我又不需要模块化编译...    搞不懂那玩意有什么用

**Comment by ZPZP1** [comment]
嗯嗯，情况应该只针对源码用模块化，好像没啥卵用

**Comment by huayanYu** [comment]
无回复,关闭. 若需要再次开启,请详细描述背景和应用场景
