### ISSUE TITLE
tdengine rs方式连接异常

### ISSUE THREAD

**Issue by hjy30312** [baomidou/dynamic-datasource#584]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.7.16

dynamic-datasource-spring-boot-starter Version(required):3.5.2

druid Version(optional):1.1.22

# Describe what happened
springboot配置文件驱动如下：
spring:
  messages:
    basename: i18n/messages
    encoding: utf-8
  datasource:
    dynamic:
      primary: postgresql #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        taos:
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.taosdata.jdbc.rs.RestfulDriver
          url: jdbc:TAOS-RS://47.1.1.1:6041/power?timezone=UTC-8&charset=UTF-8&allowMultiQueries=true
          username: root
          password: taosdata
        postgresql:
          driverClassName: org.postgresql.Driver
          password: 3zNrKLPNsTD3x3zXPqh3
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:postgresql://139.1.1.1:5432/miot
          username: postgres

问题：
    多数据源环境：
        taos用上述RS连接方式连接后，  调用taos的接口会报错，显示用的是postgresql的驱动。某些存在taos关键字语句SQL会报错
        如果taos的连接方式改为JDBC方式，则用的taos的驱动，某些存在taos关键字语句SQL不会报错
    
    单数据源环境：
       不会存在上述问题

是多数据源不能支持 tdengine的RS方式连接吗？

**Comment by huayanYu** [comment]
多数据源底层都是连接池，具体支持情况是连接池控制的。 你的情况建议你咨询连接池
