### ISSUE TITLE
4.2.0的dynamic-datasource-spring-boot3-starter/pom.xml中不应更改web容器为undertow，应由用户自己决定

### ISSUE THREAD

**Issue by DengChen2020** [baomidou/dynamic-datasource#587]
JDK Version(required): 21

SpringBoot Version(required): 3.1.5

dynamic-datasource-spring-boot-starter Version(required):4.2.0

不应更改web容器为undertow，应由用户自己决定

**Comment by huayanYu** [comment]
嗯,不知道从哪抄过来的,抄多了

**Comment by T1meMach1ne** [comment]
发现同样问题，
解决方案：当项目使用tomcat时，需要手动排除undertow
