### ISSUE TITLE
多个数据源配置后，怎么配置整个事务的超时时间啊？

### ISSUE THREAD

**Issue by e001432124** [baomidou/dynamic-datasource#591]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3.2

dynamic-datasource-spring-boot-starter Version(required):3.6.1

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by ZPZP1** [comment]
事务随着方法执行完就自动提交或者回滚了，事务超时时间有什么场景会有一些潜在的问题吧，感觉弊大于利

**Comment by liqiuh** [comment]
应该是希望设置多数据源场景下的事务的最大超时时间吧， 毕竟有时候数据源设置60s超时，如果 @DSTransactional 下存在复数的数据源操作。 到时候来个 60*N的总超时时间，确实也无法接受。
