### ISSUE TITLE
why the document need to pay?

### ISSUE THREAD

**Issue by zhonghuafy** [baomidou/dynamic-datasource#594]
请问为什么官方文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/2264611 需要付费才能查看？
May I ask why the document needs to pay?
![文档付费界面](https://github.com/baomidou/dynamic-datasource/assets/3118819/33f5086b-df23-4f6a-884d-5e3a6d703497)

**Comment by huayanYu** [comment]
why u can pay for game ,no for doc
