### ISSUE TITLE
4.2.0的dynamic-datasource-spring-boot3-starter/pom.xml web容器undertow和webTomcat冲突，websocket 无法使用

### ISSUE THREAD

**Issue by KongZouXiang** [baomidou/dynamic-datasource#600]
JDK Version(required): 21

SpringBoot Version(required): 3.2.0

dynamic-datasource-spring-boot-starter Version(required):4.2.0

![image](https://github.com/baomidou/dynamic-datasource/assets/43474763/8c790eab-39d9-468b-911b-febd01cc06b6)

![image](https://github.com/baomidou/dynamic-datasource/assets/43474763/3cb1656e-bca7-47e7-bf83-360811a9e40c)

No 'jakarta.websocket.server.ServerContainer' ServletContext attribute. Are you running in a Servlet container that supports JSR-356?

希望下个版本把undertow去掉

**Comment by KongZouXiang** [comment]
解决方案，Maven同理
![image](https://github.com/baomidou/dynamic-datasource/assets/43474763/9ea12df4-e90f-4fff-b06d-3358382ea082)

**Comment by alvinkwok1** [comment]
应该和#587是同一个问题，在最新的主线代码中undertow的依赖是去掉了的

**Comment by alvinkwok1** [comment]
先手动排除下

**Comment by huayanYu** [comment]
4.3.0
