### ISSUE TITLE
druid  testOnBorrow设置为true时，连接sqlserver  抛出异常

### ISSUE THREAD

**Issue by Ruichian** [baomidou/dynamic-datasource#601]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.4.2

dynamic-datasource-spring-boot-starter Version(required):3.5.2

druid Version(optional):1.2.5

# Describe what happened
![image](https://github.com/baomidou/dynamic-datasource/assets/52705586/7e231276-0ac2-472f-ae45-3cb4ff3d5726)
当testOnBorrow设置为true时，连接sqlserver  抛出异常
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
所以呢?

**Comment by huayanYu** [comment]
我不知道,能不能用是连接池和数据库的事情, 不是我控制能不能用的事.
