### ISSUE TITLE
SpringBoot3.2无法启动，是不是我还需要别的依赖

### ISSUE THREAD

**Issue by yymjku18** [baomidou/dynamic-datasource#606]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 17

SpringBoot Version(required): 3.2

dynamic-datasource-spring-boot-starter Version(required):

dynamic-datasource-spring-boot3-starter 4.2.0

druid Version(optional):

# Describe what happened

Expected Result:

期待正常启动

Actual Result:

无法启动并报错

If there is an exception,or aop invalid,please attach the exception trace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/baomidou/dynamic/datasource/spring/boot/autoconfigure/DynamicDataSourceAutoConfiguration.class]: dynamic-datasource create basic database named master error
```

# Steps to reproduce

- Step 1 
建立一个springboot 3.2 maven的工程

- Step 2 
pom中加入dynamic-datasource-spring-boot3-starter 4.2.0版本的依赖

- Step 3 
配置数据库连接信息并启动

**Comment by huayanYu** [comment]
不需要,自行断点排查
