### ISSUE TITLE
关于 4.2.0 dynamic-datasource 使用Amazon JDK不报错 而Oracle JDK 报错 Communications link failure

### ISSUE THREAD

**Issue by TwoCarPongPong** [baomidou/dynamic-datasource#607]
# Enviroment

JDK Version(required): Oracle JDK 1.8.0_291 & Amazon Corretto JDK 1.8.0_392

SpringBoot Version(required): 2.3.8.RELEASE

dynamic-datasource-spring-boot-starter Version(required): 4.2.0

druid Version(optional): 1.2.16
# Description

我在使用 Amazon Corretto JDK1.8.0_392 时项目正常
然后 切换到了 Oracle Open JDK1.8.0_291  这时我使用 DynamicDataSourceContextHolder.push()切换数据源 
查询时报错com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

**Comment by huayanYu** [comment]
大哥， 我只是切。 具体链接是连接池负责。 如果有问题找对应的连接池
