### ISSUE TITLE
upgrade to sbring-boot3.2.1 got wrong

### ISSUE THREAD

**Issue by huayanYu** [baomidou/dynamic-datasource#612]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  17

SpringBoot Version(required): 3.2.1

dynamic-datasource-spring-boot-starter Version(required): 4.3.0

druid Version(optional):

# Describe what happened
 in master i upgrade spring-boot to 3.2.1 and then use mvn clean install
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.743 s <<< FAILURE! -- in com.baomidou.dynamic.datasource.fixture.v1.SPELTest
[ERROR] com.baomidou.dynamic.datasource.fixture.v1.SPELTest.testSPEL -- Time elapsed: 0.032 s <<< ERROR!
com.baomidou.dynamic.datasource.exception.ErrorCreateDataSourceException: dynamic-datasource create basic database named master error
        at com.baomidou.dynamic.datasource.creator.basic.BasicDataSourceCreator.createDataSource(BasicDataSourceCreator.java:90)
        at com.baomidou.dynamic.datasource.creator.DefaultDataSourceCreator.createDataSource(DefaultDataSourceCreator.java:97)
        at com.baomidou.dynamic.datasource.fixture.v1.SPELTest.testSPEL(SPELTest.java:72)

but when i use springboot 3.1.5 it is right;

i dont known why; 

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
@linghengqian  can u help me

**Comment by linghengqian** [comment]
> but when i use springboot 3.1.5 it is right;

- Are you sure? I switched `spring-boot-dependencies.version` to `3.1.5` and `./mvnw -T1C clean test` also failed three unit tests. It looks like there were some extra changes that broke the build.
```shell
[ERROR] Errors: 
[ERROR]   DsTransactionalTest.testDsTransactional:58 » ErrorCreateDataSource dynamic-datasource create basic database named order error
[ERROR]   NestDataSourceTest.testNest:61 » ErrorCreateDataSource dynamic-datasource create basic database named master error
[ERROR]   SPELTest.testSPEL:79 » ErrorCreateDataSource dynamic-datasource create basic database named master error

```

**Comment by linghengqian** [comment]
- I verified that https://github.com/baomidou/dynamic-datasource/commit/2190df2ac328b7d082f7c2057d15485edd1efb10 is normal. But https://github.com/baomidou/dynamic-datasource/commit/8f633a5270d6fce41f4c5d1a04f99a513a437b98 is missing part of the content.
