### ISSUE TITLE
关于本地事务的一个问题

### ISSUE THREAD

**Issue by MQPearth** [baomidou/dynamic-datasource#615]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):
jdk8+
SpringBoot Version(required):
2.6.14
dynamic-datasource-spring-boot-starter Version(required):
3.5.1,4.2.0

druid Version(optional):

# Describe what happened

关于DSTransactional这个本地事务, 
假如我有A,B两库, 修改数据后通知对应数据库连接进行commit, 

A连接 接到commit, 成功, 
B连接 接到commit, 因为网络原因失败

这种情况, A库的操作能回滚吗

# Steps to reproduce

**Comment by huayanYu** [comment]
just try

**Comment by MQPearth** [comment]
okay
