### ISSUE TITLE
如何在spring-boot3中配置neo4j

### ISSUE THREAD

**Issue by yigezaici** [baomidou/dynamic-datasource#624]
# Enviroment

JDK Version(required): 17

SpringBoot Version(required): 3.2.2

dynamic-datasource-spring-boot3-starter Version(required):4.3.0

druid Version(optional):1.2.21

# Describe what happened
请问，升级springboot3如何配置neo4j，配置driver-class-name为org.neo4j.driver.Driver无法初始化

**Comment by huayanYu** [comment]
没用的时候怎么配， 用了又遇到什么错误

**Comment by yigezaici** [comment]
> 没用的时候怎么配， 用了又遇到什么错误

使用原先的neo4j-jdbc-driver包配置driver-class-name报以下错误
![image](https://github.com/baomidou/dynamic-datasource/assets/52189465/50a091ea-f856-4872-ab67-7fa75150dba6)

使用neo4j-java-driver包后，配置driver-class-name为org.neo4j.driver.Driver无法初始化

**Comment by huayanYu** [comment]
你都classNotFound了， 自己找问题
