### ISSUE TITLE
动态数据源 多数据源 hikari连接池监控指标获取不到, 亲测 非动态数据源 actuator/prometheus是有hikaricp监控指标的

### ISSUE THREAD

**Issue by fattyliu** [baomidou/dynamic-datasource#626]

**Comment by gxmgxm** [comment]
您好 ，这里是高相猛，很高兴收到您的邮件 。

**Comment by huayanYu** [comment]
需要你自己去实现actuator，多数据源没有相关指标。 比如你怎么评价整个多数据源的指标，一百个都正常才算正常？

**Comment by fattyliu** [comment]
> 需要你自己去实现actuator，多数据源没有相关指标。 比如你怎么评价整个多数据源的指标，一百个都正常才算正常？

用的是mybatisplus配置文件配置的动态数据源, @ds动态切换, 不应该是集成好的连接池吗, 如果是多个数据源, 数据源名称也是不一样的, 与多少个数据源没关系吧

**Comment by huayanYu** [comment]
我在说东你在说西， 你要解决一个核心问题，假设多数据源管理了100个数据源，怎么用actuator反馈表达连接池的监控指标。

**Comment by fattyliu** [comment]
大佬有推荐的方案吗

**Comment by fattyliu** [comment]
> 我在说东你在说西， 你要解决一个核心问题，假设多数据源管理了100个数据源，怎么用actuator反馈表达连接池的监控指标。

大佬有推荐的方案吗
