### ISSUE TITLE
版本兼容咨询

### ISSUE THREAD

**Issue by sekitj** [baomidou/dynamic-datasource#629]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  8

SpringBoot Version(required):  2.2.5

dynamic-datasource-spring-boot-starter Version(required): 3.1.1

druid Version(optional):

# Describe what happened

Expected Result:
我们在使用3.1.0/3.1.1改造多数据源动态切换时，发现sharding-jdbc的数据源注入有问题，一直是失败的。
在看云文档中有写，3.1.0有BUG，想咨询一下，如果直接把dynamic-datasource-spring-boot-starter Version升级到3.5.2（此版本被标记为稳定版本），是否完全兼容3.1.0/3.1.1

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
just try
