### ISSUE TITLE
原有配置排除异常导致项目无法启动

### ISSUE THREAD

**Issue by 12341234-yangboran** [baomidou/dynamic-datasource#634]
# Enviroment

JDK Version(required): 
17
SpringBoot Version(required): 
3.2.4
dynamic-datasource-spring-boot-starter Version(required):
4.3.0
druid Version(optional):
1.2.22

# Describe what happened
![image](https://github.com/baomidou/dynamic-datasource/assets/74187378/5f2fcd5b-3dc5-48a8-8d3b-41a1039e2aa9)
![image](https://github.com/baomidou/dynamic-datasource/assets/74187378/71767c60-032c-4286-a3f1-00d8d8b8f74d)

Expected Result:
原因是项目需要druid管理页面，希望按照配置可以有效显示

**Comment by 12341234-yangboran** [comment]
还有一个问题，dynamic-datasource-spring-boot3-starter是给spring-boot-dependencies3.0以上版本使用的吗？

**Comment by huayanYu** [comment]
嗯
