### ISSUE TITLE
the doc need buy?????????????????

### ISSUE THREAD

**Issue by evangoe** [baomidou/dynamic-datasource#641]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3 

![image](https://github.com/baomidou/dynamic-datasource/assets/13144973/16a691c7-f950-4759-8a39-03b2a1492fe0)
ju'r居然阅读文档还要钱？？？？？？？？？？？？？？？

**Comment by huayanYu** [comment]
对啊~  居然认为花钱不合理。
