### ISSUE TITLE
4.3.0版本 使用clickhouse 设置 initial-size 参数会无法启动

### ISSUE THREAD

**Issue by oxcz** [baomidou/dynamic-datasource#644]
# Enviroment

JDK Version(required): 
17
SpringBoot Version(required): 
2.11.3
dynamic-datasource-spring-boot-starter Version(required):
4.3.0
druid Version(optional):
1.2.22

# Describe what happened
引入clickhouse依赖
 <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.6.0-patch4</version>
 </dependency>
设置spring.datasource.dynamic.druid.initial-size 
然后正常启动项目，报错
<img width="1410" alt="image" src="https://github.com/baomidou/dynamic-datasource/assets/16790410/bd7e23af-ca6d-447d-8e6e-b5f27717af6c">

**Comment by huayanYu** [comment]
没用过那玩意，建议直接参与PR，或者等待有缘人查看，我这里只负责设置参数
