### ISSUE TITLE
开启多数据源后无法打印sql日志，请问该怎么配置呢？

### ISSUE THREAD

**Issue by oxcz** [baomidou/dynamic-datasource#647]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
idk 17
SpringBoot Version(required): 
3.2.4

dynamic-datasource-spring-boot-starter Version(required):
4.3.0

druid Version(optional):
1.2.2

# Describe what happened
可以正常打印sql日志

Expected Result:
未打印sql日志

# Steps to reproduce
项目使用的是bladex的那个框架，引入了动态数据源依赖。
项目使用拦截器对日志进行打印
![image](https://github.com/baomidou/dynamic-datasource/assets/16790410/024de87b-f3e7-4628-9e05-c8a7436788bb)
看到框架中已经对数据源日志打印进行了配置，但是实际上未生效。
![image](https://github.com/baomidou/dynamic-datasource/assets/16790410/09b386db-594a-4afe-9440-768c88cfcfe1)
有尝试手工加入这个配置，但是仍未生效，请问该怎么配置输出打印比较好呢？

**Comment by huayanYu** [comment]
找bladex，我只负责切数据源

**Comment by oxcz** [comment]
> 找bladex，我只负责切数据源

如果是直接集成的，怎么打印日志呀？现在文档怎么买呀，加了微信也没通过。

**Comment by oxcz** [comment]
proxy-filters: sqlLogInterceptor
bladex是增加这个配置
proxy-filters: 
 -sqlLogInterceptor
这种格式是不生效的
