### ISSUE TITLE
创建数据源错误

### ISSUE THREAD

**Issue by fenmirs** [baomidou/dynamic-datasource#653]
# Enviroment

JDK Version(required): oracle jdk 17

SpringBoot Version(required): 3.3.1

dynamic-datasource-spring-boot-starter Version(required): 4.3.1

druid Version(optional): 无

# Describe what happened

Expected Result: 
正常启动项目

Actual Result:
创建数据源失败，并且错误没有抛出来

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```
![image](https://github.com/baomidou/dynamic-datasource/assets/7390486/c6422602-1432-4c5f-b945-b557edc405c9)

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by fenmirs** [comment]
代码中的buildMethod.invoke  实际执行 org.springframework.boot.jdbc.DataSourceBuilder 的 build 方法；
当发生错误时，你这里将异常捕获后转为自定义的错误信息；并未打印异常堆栈，导致无法继续跟踪错误原因

**Comment by alvinkwok1** [comment]
我检查了下其他的数据源创建逻辑，对于数据源创建失败处理上并不一致。
1. beecp： 未做异常捕获
2. dbcp2： 未做异常捕获
3. druid: 异常捕获后重新包装返回
4. Hikari： 未做异常捕获。
5. basic，做了异常捕获，但是未传递异常栈

是否有必要统一处理逻辑全部将创建异常包装为ErrorCreateDataSourceException向上返回？

**Comment by huayanYu** [comment]
可以统一一下，druid有点麻烦，有重连和最多重试什么的。 不知道怎么兼容

**Comment by alvinkwok1** [comment]
@huayanYu 指派给我吧，我尝试能将处理的地方都做一下
