### ISSUE TITLE
添加polardb的数据源，分页查询提示other database not supported

### ISSUE THREAD

**Issue by shijiaowang** [baomidou/dynamic-datasource#654]
现在用的是3.5.3.1的版本，使用polardb数据源分页查询会提示other database not supported，查看DbType里没有这个polardb相关的枚举，能添加吗，或者可以让用户在yml里动态添加。

**Comment by alvinkwok1** [comment]
提供的信息不是很准确，本项目没有3.5.3的release版本。 

从描述上看, 你应该使用的是Druid吧，我看本项目对应的druid版本对应的DbType中是支持polardb的。通过指定前缀是可以自动识别配置的

![image](https://github.com/user-attachments/assets/4a0a27cf-8bcd-4ec6-8794-65fc0b68a9cf)

可以提供更多信息看下，但是我觉得这个应该是连接池或者你使用的分页插件的问题。
