### ISSUE TITLE
事务注解不生效问题

### ISSUE THREAD

**Issue by banliangxingkong** [baomidou/dynamic-datasource#656]
@DSTransactional(propagation = DsPropagation.REQUIRES_NEW) 事务注解不生效问题

多个查询语句，多数据源，然后其中有个查询语句超时，事务注解不生效

**Comment by banliangxingkong** [comment]
版本号是  4.2.0

**Comment by huayanYu** [comment]
给出示例，重新提问。

**Comment by banliangxingkong** [comment]
多数据源事务注解 @DSTransactional(propagation = DsPropagation.REQUIRES_NEW) 数据库连接超时不生效
![控制台报错1](https://github.com/user-attachments/assets/6cab794b-0455-4088-8260-0f8a2c27cdfa)


![版本号](https://github.com/user-attachments/assets/2bb0d0f1-e7e7-4718-b95c-dfc30897e071)
![代码示例](https://github.com/user-attachments/assets/1eb95d6e-3c50-4a93-9fbb-e596033b505b)
![控制台报错](https://github.com/user-attachments/assets/a4877ea6-f61a-4951-a395-7d9ecfb5e103)
