### ISSUE TITLE
事务注解不生效问题

### ISSUE THREAD

**Issue by banliangxingkong** [baomidou/dynamic-datasource#662]
多数据源事务注解 @DSTransactional(propagation = DsPropagation.REQUIRES_NEW) 数据库连接超时不生效

# Enviroment

JDK Version(required):     17

SpringBoot Version(required):     3.2.0

dynamic-datasource-spring-boot-starter Version(required):     4.2.0

druid Version(optional):    mysql8.0    oracle11

# Describe what happened
@DSTransactional(propagation = DsPropagation.REQUIRES_NEW) 数据库连接超时不生效

Expected Result:
![版本号](https://github.com/user-attachments/assets/f669b9b5-b30b-42c5-928a-c2a1d5e648ba)

![代码示例](https://github.com/user-attachments/assets/21cd4af1-b304-4798-a561-fa26b68f0980)
![控制台报错1](https://github.com/user-attachments/assets/835799fa-c75b-4750-b21e-16b913682c51)
![控制台报错](https://github.com/user-attachments/assets/890c6dac-6a4b-46fd-9ad3-4193aa3dd04b)

**Comment by alvinkwok1** [comment]
1. 是多库事务吗？ 
2. 你的数据库操作逻辑和事务开启逻辑是怎么样的？具体的失效是哪个没有回滚？
3. 有没有因为错误的使用导致AOP失效？

**Comment by banliangxingkong** [comment]
1.是多库的查询事务
2.只涉及查询，因为我把虚拟机的oracle 的数据库停止了，然后连接超时，就不会继续查下面的数据，控制台一直输出截图的报错了
3.我把数据库连接可能超时的地方进行try catch 捕获异常了，别的并没有做别的操作

**Comment by banliangxingkong** [comment]
这一个方法里面  包含了七个小方法，每个方法对应一个sql查询，然后每个方法都try catch了一下，有几个小方法是查询的oracle 数据库，连接不上oracle数据库，然后控制台就有socket time out，但是事务注解没有生效，大概半个月之前吧还是生效的

**Comment by alvinkwok1** [comment]
@banliangxingkong 最好是脱敏后给出问题代码，不然不知道怎么做复现。
