### ISSUE TITLE
数据源切换失效

### ISSUE THREAD

**Issue by PurgatoryMessenger** [baomidou/dynamic-datasource#663]
jdk：17
SpringBoot：2.7
数据源：MySQL+MySQL
复现：随便创建两个数据源，master和slave1，在slave1的service层方法中，调用master的service层方法，在master的serviceImpl中写代码逻辑，返回数据，这个时候直接调用slave1的方法，会报错slave1.table不存在
PS：slave的serviceImpl类上写了@DS注解
PPS：网上查到的都是事务导致的切换失效，但是master和slave的方法都只是查询

**Comment by PurgatoryMessenger** [comment]
前提是master的service没有添加@DS注解，加了@DS注解是正常的，但是默认本来不就应该是master吗

**Comment by huayanYu** [comment]
按模板提问。

**Comment by huayanYu** [comment]
附图
