### ISSUE TITLE
能否引入transmittable-thread-local或者其他，解决异步执行时上下文传递的问题

### ISSUE THREAD

**Issue by KongZouXiang** [baomidou/dynamic-datasource#664]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 21

SpringBoot Version(required): 3.3.0

dynamic-datasource-spring-boot-starter Version(required): 4.3.1

druid Version(optional):

# Describe what happened

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
你需要就自己改源码加， 我不想加。
