### ISSUE TITLE
jdbc连接参数rewriteBatchedStatements对多数据源无效

### ISSUE THREAD

**Issue by weijie0** [baomidou/dynamic-datasource#666]
# Enviroment

JDK Version(required): 
17
SpringBoot Version(required): 
3
dynamic-datasource-spring-boot-starter Version(required):
4.3.1
druid Version(optional):

# Describe what happened
mybatisplus>ServiceImpl>saveBatch方法执行慢，rewriteBatchedStatements不起作用，不使用多数据源生效

Expected Result:

可以批量操作

Actual Result:
批量执行慢

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by weijie0** [comment]
@huayanYu 直接close是什么意思，如何解决呢，大佬

**Comment by huayanYu** [comment]
不知道，提问太潦草。 根据经验和多数据源无关

**Comment by weijie0** [comment]
<img width="905" alt="image" src="https://github.com/user-attachments/assets/6f43ae40-c8ff-492f-8053-09b9fdf5aaa3">

**Comment by weijie0** [comment]
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/cb54491d-706d-4347-8d9f-5402dca54815">

**Comment by weijie0** [comment]
@huayanYu 正常批量插入saveBatch方法，并且jdbc参数rewriteBatchedStatements，会只有一条insert语句，但是如上图，插入一千条数据，执行了1000次insert
