### ISSUE TITLE
注解与LocalTxUtil混用多段事务时报错 "connectionProxyMap" is null

### ISSUE THREAD

**Issue by ChiMuYuan** [baomidou/dynamic-datasource#667]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
jdk17

SpringBoot Version(required): 
springboot3

dynamic-datasource-spring-boot-starter Version(required):
        <dynamic-datasource-spring-boot3-starter.version>4.3.1</dynamic-datasource-spring-boot3-starter.version>

druid Version(optional):
        <druid-spring-boot-3-starter.version>1.2.23</druid-spring-boot-3-starter.version>

# Describe what happened
DSTransactional开启的事务中途提交后，开启第二段事务不做手动提交时报错。
现在业务中不适用注解，两段事务都采用`LocalTxUtil.startTransaction()`手动开启,并使用`LocalTxUtil.commit(TransactionContext.getXID());`手动结束可避免。
碰到这种注解和手动开启混用情况下bug，看需不需要改吧

Expected Result:
```
TransactionalTemplate.doExecute {
        String xid = LocalTxUtil.startTransaction();
        .....
        LocalTxUtil.commit(xid);  ——> LocalTxUtil.commit(TransactionContext.getXID());
        ....
        LocalTxUtil.rollback(xid); ——>  LocalTxUtil.rollback(TransactionContext.getXID());
        ....
}
```

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "connectionProxyMap" is null
	at com.baomidou.dynamic.datasource.tx.ConnectionFactory.notify(ConnectionFactory.java:150)
	at com.baomidou.dynamic.datasource.tx.LocalTxUtil.commit(LocalTxUtil.java:91)
	at com.baomidou.dynamic.datasource.tx.TransactionalTemplate.doExecute(TransactionalTemplate.java:126)
	at com.baomidou.dynamic.datasource.tx.TransactionalTemplate.execute(TransactionalTemplate.java:94)
	at com.baomidou.dynamic.datasource.aop.DynamicLocalTransactionInterceptor.invoke(DynamicLocalTransactionInterceptor.java:59)
```

# Steps to reproduce

- Step 1 
```
    @DSTransactional
    @GetMapping("/test")
    public void test() throws Exception {
        Long id = IdWorker.getId();
        testTableService.save(new TestTable().setId(id));
        LocalTxUtil.commit(TransactionContext.getXID());
        
        LocalTxUtil.startTransaction();
        testTableService.updateById(new TestTable().setId(id).setOpTest("123"));
    }
```

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
不改了
