### ISSUE TITLE
如果我不用@DSTransactional注解，可以在代码里手动开启多数据源的事务吗

### ISSUE THREAD

**Issue by lhao-ux** [baomidou/dynamic-datasource#668]
# Enviroment

JDK Version(required): 17

SpringBoot Version(required): 3.2.2

dynamic-datasource-spring-boot-starter Version(required):3.6.1

druid Version(optional):

# Describe what happened
您们好如果我不用@DSTransactional注解，可以在代码里手动开启多数据源的事务吗

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
可以，自己研究
