### ISSUE TITLE
可选依赖是否不对？

### ISSUE THREAD

**Issue by GongLe** [baomidou/dynamic-datasource#669]
# Enviroment

JDK Version(required): 

SpringBoot Version(required): 

dynamic-datasource-spring-boot-starter Version(required):
![Clip_2024-08-28_08-47-56](https://github.com/user-attachments/assets/4b1da054-866b-48e2-a65d-c29df75e332e)

druid Version(optional):

# Describe what happened

Expected Result:

可选依赖class在公共class中，得强制一起来进项目？

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 
- 
![Clip_2024-08-28_08-46-39](https://github.com/user-attachments/assets/b936e898-9b90-48b4-9970-cdaf43a7ccff)

![Clip_2024-08-28_08-46-29](https://github.com/user-attachments/assets/f195915d-817b-42cb-aa63-be7722be3881)

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
正常的
