### ISSUE TITLE
dynamic-datasource不支持c3p0的集成

### ISSUE THREAD

**Issue by dulinanaaa** [baomidou/dynamic-datasource#670]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): jdk8

SpringBoot Version(required): 2.7.18

dynamic-datasource-spring-boot-starter Version(required):3.5.2

druid Version(optional):1.2.16

# Describe what happened
dynamic-datasource只支持Druid，HikariCp，BeeCp,Dbcp2的快速集成么？比如GoldenDB数据库默认对c3p0的兼容性和性能支持最好，那dynamic-datasource有无对c3p0的支持呢

**Comment by huayanYu** [comment]
没有，你可以参考源码自己写一个creater就是了，如果觉得写得好也可以提交PR
