### ISSUE TITLE
异常线程池里面会存在需要使用动态数据源的情况能否支持下

### ISSUE THREAD

**Issue by Bestfeel** [baomidou/dynamic-datasource#673]
我看你源码使用的是ThreadLocal，我们在实际业务中，和一些异步重试框架里面结合，动态数据源切换会失效。这块的切换看是否需要换成TransmittableThreadLocal 的方式支持。 这个问题我们踩到坑就是一个大故障，辛苦帮忙看下。

public final class DynamicDataSourceContextHolder {
    private static final ThreadLocal<Deque<String>> LOOKUP_KEY_HOLDER = new NamedThreadLocal<Deque<String>>("dynamic-datasource") {
     .......
    public static void clear() {
        LOOKUP_KEY_HOLDER.remove();
    }
}

**Comment by huayanYu** [comment]
不打算支持，由需要自己本地改
