### ISSUE TITLE
分组数据源负载的问题请教

### ISSUE THREAD

**Issue by lgliugeng** [baomidou/dynamic-datasource#676]
# Enviroment

JDK Version(required): 17

SpringBoot Version(required): springboot3

dynamic-datasource-spring-boot-starter Version(required): 4.2

druid Version(optional):1.2.22

你好，当我使用如下配置进行动态数据访问时,进行动态数据源切换会进入分组数据源的负载中，导致通过@DS注解无法准确找到所需的数据源。因此想请教下是不是只能通过修改配置的数据源名称不进行分组还是有其他的配置能避免这样的分组问题？

##
spring:
  datasource:
    dynamic:
      primary: sunny_admin
      strict: false
      datasource:
        sunny_admin:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: 
          username: 
          password: 
        sunny:
         driver-class-name: com.mysql.cj.jdbc.Driver
          url: 
          username: 
          password: 
        sunny_trace:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: 
          username: 
          password: 
![image](https://github.com/user-attachments/assets/20e42342-a117-425c-ab7f-3ffaf6fda729)

**Comment by huayanYu** [comment]
只能通过修改配置的数据源名称不进行分组
