### ISSUE TITLE
多数据源配置postgre数据库时，currentSchema不生效

### ISSUE THREAD

**Issue by 58711060702qq** [baomidou/dynamic-datasource#678]
您好，在多数据源中配置使用postgre数据库时，在URL连接串中通过currentSchema方式指定了要访问的模式，但是mapper查询中并没有生效，并且由于多配置环境下schema不同，也不能直接在mapper.xml中写死。这个还有其他方式可以配置吗？配置截图及报错如下：
![image](https://github.com/user-attachments/assets/c8bcc2db-03b0-4a84-870d-462d9943e2c4)
![image](https://github.com/user-attachments/assets/34dffca8-153e-4692-8906-6b933689da0b)
![image](https://github.com/user-attachments/assets/4d83be2c-9c85-46dc-8c0d-8b0563ac24c5)

**Comment by huayanYu** [comment]
无法复现哦，那个参数是直接设置进连接池的，你自己检查连接池参数。
