### ISSUE TITLE
请问是否考虑提供一个编程式事务方法

### ISSUE THREAD

**Issue by 1455668754** [baomidou/dynamic-datasource#681]
大佬 请问是否考虑提供一个编程式事务方法；
类似TransactionTemplate的方式
   @Autowired
   private TransactionTemplate transactionTemplate;
   
   ...
   
   public void save(final User user) {
         transactionTemplate.execute((status) => {
            doSameThing...
            return Boolean.TRUE;
         })
   }

**Comment by huayanYu** [comment]
不考虑，已经越来越复杂了。你可以自己实现
