### ISSUE TITLE
使用动态数据源，请求连接时长超过10秒，如何配置？

### ISSUE THREAD

**Issue by zuxinpeng** [baomidou/dynamic-datasource#685]
The last packet sent successfully to the server was 10,014 milliseconds ago；
配置参数queryTimeout=30，请求又会在使用10s后被关闭，
报错是：
Caused by: java.sql.SQLException: No operations allowed after statement closed

尝试了配置各种参数
      druid:
        initial-size: 20
        min-idle: 5
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;connectTimeout=30000;socketTimeout=30000"
        ## 单位秒
        queryTimeout: 30

超过10s仍会报这个错误；

**Comment by huayanYu** [comment]
druid的问题自己排查。
