### ISSUE TITLE
rabbitmq结合多数据源切换存在问题

### ISSUE THREAD

**Issue by EightMonth** [baomidou/dynamic-datasource#686]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): JDK 8

SpringBoot Version(required): 2.7.10

dynamic-datasource-spring-boot-starter Version(required):4.1.3

druid Version(optional):

# Describe what happened

Expected Result:
数据源切换成功

Actual Result:
数据源切换失败

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 
程序连接4个数据源，分别为master、proj、app、module，主数据源为：master

- Step 2 
rabbitmq存在4个消息，消息体中存在datasource属性，用于在消费时指定数据源，例如：{"datasource":"proj","name":"123456"}
4 个消息中，其中一个消息体的datasource指定是的不存在的数据，如{"datasource":"rpg","name":"123456"},其它三个消息体指定的数据源分别是proj、app、module。

- Step 3 
进行消费时，使用以下代码进行数据源切换
```
DynamicDataSourceContextHolder.clear();
DynamicDataSourceContextHolder.push("proj");
```
第一次消费了数据源指定为proj的消息，成功变更业务库
第二次消费了数据源指定为app的消息，成功变更业务库
第三次消费了数据源指定为module的消息，成功变更业务库

第三次消费了数据源指定为rpg的消息，结果却变更了module的业务库

**Comment by huayanYu** [comment]
自己排查，除非你确定多数据源有逻辑问题。
