### ISSUE TITLE
MasterSlaveAutoRoutingPlugin 增删改不能指定数据库只能是主库

### ISSUE THREAD

**Issue by boligutou** [baomidou/dynamic-datasource#687]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.7.18
dynamic-datasource-spring-boot-starter Version(required):
4.3.1
druid Version(optional):

1.2.23

![image](https://github.com/user-attachments/assets/42f1f2ec-072a-44f5-9518-f54f6fc9c097)

# Describe what happened

insert udpate delete 时，先取数据源，后走拦截器，操作的是主库master
select时，先走拦截器，后去数据源，查询的是指定的库
Expected Result:
能不能insert，update， deete，query 都操作指定的库?

求大神！

**Comment by huayanYu** [comment]
源码这么点，自己改一个不就好。
