### ISSUE TITLE
您好，请问dynamicDataSource如何兼容shardingjdbc的读写分离 ？

### ISSUE THREAD

**Issue by zhuzhiquan** [baomidou/dynamic-datasource#690]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required): 
1.8
SpringBoot Version(required): 
2.7.18
dynamic-datasource-spring-boot-starter Version(required):
3.2.1
druid Version(optional):

# Describe what happened
动态数据源如何支持shardingjdbc的读写分离？目前只看到了支持shardingjdbc下单个数据源的分表策略

Expected Result:

支持hardingjdbc的多个数据源的读写分离

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
找shardingjdbc
